mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
]

mysite/polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),

    path('<int:pk>/', views.DetailView.as_view(), name='detail'),

    path('suggestions/', views.addSuggestion, name='suggestion'),
    # path('suggestions/', views.SuggestionView.as_view(), name='suggestion'),

    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),

    path('<int:question_id>/vote/', views.vote, name='vote'),
]

mysite/polls/models.py
from django.db import models

import datetime
from django.db import models
from django.utils import timezone

# Create your models here.

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now
        # return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self):
        return self.choice_text

class Suggestion(models.Model):
    suggestion_text = models.CharField(max_length=200)
    def __str__(self):
        return self.suggestion_text

mysite/polls/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader
from django.utils import timezone
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic
from .models import Choice, Question, Suggestion
from django import forms

class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """Return the last five published questions (not including those published in the future). """
        return Question.objects.filter(
            pub_date__lte=timezone.now()
        ).order_by('-pub_date')[:5]
        
    

class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'

    def get_queryset(self):
        """
        Excludes any questions that aren't published et.
        """
        return Question.objects.filter(pub_date__lte=timezone.now())

# class SuggestionView(generic.DetailView):
#     model = Suggestion
#     # def 
#     # return(HttpResponse("At suggestions"))
#     template_name = 'polls.suggestion.html'

def suggestion(request):
    suggestion_list = Suggestion.objects.all()
    # response = "You're looking at the suggestions"
    # return HttpResponse(response)
    context = {'suggestion_list': suggestion_list,
    'form': SuggestionForm}
    return render(request, 'polls/suggestion.html', context)

def addSuggestion(request):
    # if(request.method == 'Suggestion'):
    if request.POST.get('suggestion_text'):
        new_suggestion = Suggestion()
        new_suggestion.suggestion_text = request.POST.get('suggestion_text')
        new_suggestion.save()
        suggestion_list = Suggestion.objects.all()
        context = {'suggestion_list': suggestion_list,
        'form': SuggestionForm}

        return render(request, 'polls/suggestion.html', context)
    else:
        return render(request, 'polls/suggestion.html')


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'


class SuggestionForm(forms.ModelForm):
    class Meta:
        model = Suggestion
        fields = ('suggestion_text',)

# def index(request):
#     latest_question_list = Question.objects.order_by('-pub_date')[:5]
#     context = {'latest_question_list': latest_question_list}
#     return render(request, 'polls/index.html', context)


# # def index(request):
# #     return HttpResponse("Hello, world. You're at the polls index.")


# def detail(request, question_id):
#     question = get_object_or_404(Question, pk=question_id)
#     return render(request, 'polls/detail.html', {'question': question})
    
#     # try:
#     #     question = Question.objects.get(pk=question_id)
#     # except Question.DoesNotExist:
#     #     raise Http404("Question does not exist")

#     # return render(request, 'polls/detail.html', {'question': question})

# def results(request, question_id):
#     question = get_object_or_404(Question, pk=question_id)
#     return render(request, 'polls/results.html', {'question': question})
#     # response = "You're looking at the results of question %s."
#     # return HttpResponse(response % question_id)

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'polls/detail.html', { 'question': question,
        'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()

        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))


    # return HttpResponse("You're voting on question %s." % question_id)

# def suggest(request):
#     suggestion = get_object_or_404(Suggestion)
#     try:

mysite/polls/templates/polls/detail.html
<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
{% endfor %}
<input type="submit" value="Vote">
</form>

mysite/polls/templates/polls/index.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">


{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
    <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

<form action="/polls/suggestions/" method="post">
    {% csrf_token %}
    <label for="suggestion_text">Enter a suggestion for a new poll: </label>
    <input id="suggestion_text" type="text" name="suggestion_text" value="Suggestion">
    {{ form.as_p }} 
    <input type="submit" value="OK">
</form>

mysite/polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>

mysite/polls/templates/polls/suggestion.html
<!-- <h1>{{Suggestions}}</h1>

<p>
    Suggestions
</p>
<ul>
    {% for suggestion in suggestion_set.all %}
    <li>{{ suggestion.suggestion_text }}</li>
{% endfor %}
</ul> -->


<table>
    <tr>
        <th>Suggestions</th>
    </tr>
    {% for item in suggestion_list %}
    <tr>
        <td>{{ item.suggestion_text}}</td>
    </tr>
    {% endfor %}
</table>